[package]
name = "nutmeg"
version = "0.0.0"
edition = "2021"
description = "Draw flexible progress bars and console output"
license = "MIT"
repository = "https://github.com/sourcefrog/nutmeg"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
crossterm = "0.23"
yansi = "0.5"
